STAGES = [
    [
        'treatment_bp',
        'treatment_lipid'
    ],
    [
        'progression_sbp_pre_tx',
        'progression_sbp_post_tx',
        'progression_dbp_pre_tx',
        'progression_dbp_post_tx'
    ],
    [
        'progression_sbp',
        'progression_dbp'
    ],
    [
        'progression_bmi',
        'progression_ldl',
        'progression_insulin_dose',
        'progression_hr',
        'progression_hba1c',
        'progression_trig',
        'progression_hdl',
        'progression_smoker'
    ],
    [
        'progression_quit_smoking'
    ],
    [
        'progression_totchol',
        'progression_hypertension'
    ],
    [
        'complication_npdr',
        'complication_esrd',
        'complication_dpn',
        'complication_microalbuminuria',
        'complication_pdr',
        'complication_hypoglycemia',
        'complication_macroalbuminuria',
        'complication_amputation',
        'complication_cvd_non_mace',
        'complication_ulcer',
        'complication_cvd_mace',
        'complication_dka',
        'complication_csme',
        'complication_blindness',
        # 'complication_depression'
    ],
    # if an individual develops esrd they also have gfr; gfr needs to be executed after esrd
    [
        'complication_gfr'
    ],
    [
        'complication_cvd',
    ],
    [
        'mortality_cvd_mace_death',
        'mortality_cvd_non_mace_death',
        'mortality_non_cvd_death'
    ],
    [
        'mortality_death',
    ],
    [
        "metabolism_age",
        "metabolism_lifespan"
    ],
    [
        'economics_health_cost',
        'economics_event_cost',
        'economics_intervention_cost'
    ],
    [
        'economics_overall_cost',
        'economics_qaly'
    ]
]


__all__ = [
    'progression_bmi',
    'progression_ldl',
    'progression_insulin_dose',
    'progression_hr',
    'progression_hba1c',
    'progression_sbp',
    'progression_dbp',
    'progression_sbp_pre_tx',
    'progression_sbp_post_tx',
    'progression_trig',
    'progression_dbp_pre_tx',
    'progression_dbp_post_tx',
    'progression_hdl',
    'progression_smoker',
    'progression_totchol',
    'progression_hypertension',
    'complication_npdr',
    'complication_esrd',
    'complication_dpn',
    'complication_cvd',
    'complication_microalbuminuria',
    'complication_pdr',
    'complication_hypoglycemia',
    'complication_macroalbuminuria',
    'complication_amputation',
    'complication_cvd_non_mace',
    'complication_ulcer',
    'complication_cvd_mace',
    'complication_gfr',
    'complication_dka',
    'complication_csme',
    'mortality_cvd_mace_death',
    'mortality_cvd_non_mace_death',
    'mortality_non_cvd_death',
    'mortality_death',
    'metabolism_age',
    'metabolism_lifespan',
    'economics_cost',
    'economics_qaly',
    'treatment_bp',
    'treatment_lipid'
]
